#!/usr/bin/env python3
"""
Performance Visualization Script for Yetter AI Image Generation Comparison

This script analyzes summary reports and batch results from different AI image generation providers
to create comparative visualizations for performance metrics.

Author: Generated by Claude Code
Date: August 2025
"""

import os
import json
import re
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pathlib import Path
from typing import Dict, List, Tuple, Optional

# Set up plotting style
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")

class PerformanceAnalyzer:
    """Analyzes AI image generation performance data from multiple providers."""
    
    def __init__(self):
        self.data = []
        self.providers = ['fal', 'replicate', 'runware', 'wavespeed', 'model']
        self.models = ['flux-1-dev', 'flux-1-kontext-dev', 'qwen-image']
        
    def parse_summary_report(self, file_path: str) -> Optional[Dict]:
        """Parse a summary report markdown file to extract performance metrics."""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            data = {}
            
            # Extract average time per image
            time_per_image_match = re.search(r'Average time per image:\s*([\d.]+)s', content)
            if time_per_image_match:
                data['avg_time_per_image'] = float(time_per_image_match.group(1))
            else:
                # Try alternative pattern from different report formats
                time_per_image_match = re.search(r'Time per image:\s*([\d.]+)s', content)
                if time_per_image_match:
                    data['avg_time_per_image'] = float(time_per_image_match.group(1))
                else:
                    # Calculate from average time per prompt (assuming 1 image per prompt)
                    avg_prompt_match = re.search(r'Average time per prompt:\s*([\d.]+)s', content)
                    if avg_prompt_match:
                        data['avg_time_per_image'] = float(avg_prompt_match.group(1))
            
            # Extract total time for 10 images
            total_time_match = re.search(r'Total time for 10 images:\s*([\d.]+)s', content)
            if total_time_match:
                data['total_time_10_images'] = float(total_time_match.group(1))
            else:
                # Try alternative patterns
                model_exec_match = re.search(r'Total model execution time:\s*([\d.]+)s', content)
                if model_exec_match:
                    data['total_time_10_images'] = float(model_exec_match.group(1))
                else:
                    total_match = re.search(r'Total time:\s*([\d.]+)s', content)
                    if total_match:
                        data['total_time_10_images'] = float(total_match.group(1))
            
            return data
            
        except Exception as e:
            print(f"Error parsing summary report {file_path}: {e}")
            return None
    
    def parse_batch_results(self, file_path: str) -> Optional[Dict]:
        """Parse batch results JSON file to extract individual timings."""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            results = {
                'individual_times': [],
                'first_image_time': None,
                'total_time': None
            }
            
            # Extract individual execution times
            if 'results' in data:
                for result in data['results']:
                    if result.get('success', False):
                        exec_time = result.get('executionTime')
                        if exec_time is not None:
                            results['individual_times'].append(exec_time)
                
                # First image time (waiting time for first generation)
                if data['results'] and data['results'][0].get('success', False):
                    results['first_image_time'] = data['results'][0].get('executionTime')
            
            # Total execution time
            if 'totalModelExecutionTime' in data:
                results['total_time'] = data['totalModelExecutionTime']
            elif 'totalExecutionTime' in data:
                results['total_time'] = data['totalExecutionTime']
            
            return results
            
        except Exception as e:
            print(f"Error parsing batch results {file_path}: {e}")
            return None
    
    def collect_data(self):
        """Collect data from all summary reports and batch results."""
        print("Collecting performance data from all providers and models...")
        
        for provider in self.providers:
            for model in self.models:
                # Determine the correct path based on provider
                if provider == 'model':
                    base_path = f"model/{model}/results"
                else:
                    base_path = f"control_group/{provider}/{model}/results"
                
                summary_path = f"{base_path}/summary_report.md"
                json_path = f"{base_path}/batch_results.json"
                
                if os.path.exists(summary_path):
                    print(f"Processing {provider}/{model}...")
                    
                    # Parse summary report
                    summary_data = self.parse_summary_report(summary_path)
                    
                    # Parse JSON results
                    json_data = None
                    if os.path.exists(json_path):
                        json_data = self.parse_batch_results(json_path)
                    
                    # Combine data
                    if summary_data or json_data:
                        record = {
                            'provider': 'yetter' if provider == 'model' else provider,
                            'model': model,
                            'provider_model': f"{provider}_{model}",
                        }
                        
                        if summary_data:
                            record.update(summary_data)
                        
                        if json_data:
                            record['individual_times'] = json_data['individual_times']
                            if json_data['first_image_time'] is not None:
                                record['first_image_time'] = json_data['first_image_time']
                            if json_data['total_time'] is not None and 'total_time_10_images' not in record:
                                record['total_time_10_images'] = json_data['total_time']
                        
                        self.data.append(record)
                else:
                    print(f"Warning: {summary_path} not found")
        
        print(f"Collected data from {len(self.data)} provider/model combinations")
    
    def create_box_plot_time_per_image(self):
        """Create box plot for time per image generation."""
        print("Creating box plot for time per image generation...")
        
        # Prepare data for box plot
        plot_data = []
        for record in self.data:
            if 'individual_times' in record and record['individual_times']:
                for time in record['individual_times']:
                    plot_data.append({
                        'Provider': record['provider'],
                        'Model': record['model'],
                        'Time (seconds)': time
                    })
        
        if not plot_data:
            print("No individual timing data available for box plot")
            return
        
        df = pd.DataFrame(plot_data)
        
        # Create the plot
        fig, axes = plt.subplots(1, 3, figsize=(18, 6))
        fig.suptitle('Time per Image Generation - Box Plot Comparison', fontsize=16, fontweight='bold')
        
        for i, model in enumerate(self.models):
            model_data = df[df['Model'] == model]
            
            if not model_data.empty:
                sns.boxplot(data=model_data, x='Provider', y='Time (seconds)', ax=axes[i])
                axes[i].set_title(f'{model}', fontweight='bold')
                axes[i].set_xlabel('Provider')
                axes[i].set_ylabel('Time (seconds)')
                axes[i].tick_params(axis='x', rotation=45)
                
                # Add sample size annotations
                providers = model_data['Provider'].unique()
                for j, provider in enumerate(providers):
                    provider_data = model_data[model_data['Provider'] == provider]
                    count = len(provider_data)
                    axes[i].text(j, axes[i].get_ylim()[1] * 0.95, f'n={count}', 
                               ha='center', va='top', fontsize=10, fontweight='bold')
        
        plt.tight_layout()
        plt.savefig('plots/time_per_image_boxplot.png', dpi=300, bbox_inches='tight')
        plt.show()
        print("Box plot saved as 'plots/time_per_image_boxplot.png'")
    
    def create_total_time_plot(self):
        """Create bar chart for total time for 10 image generation."""
        print("Creating bar chart for total time for 10 images...")
        
        # Prepare data
        plot_data = []
        for record in self.data:
            if 'total_time_10_images' in record:
                plot_data.append({
                    'Provider': record['provider'],
                    'Model': record['model'],
                    'Total Time (seconds)': record['total_time_10_images']
                })
        
        if not plot_data:
            print("No total time data available")
            return
        
        df = pd.DataFrame(plot_data)
        
        # Create the plot
        fig, ax = plt.subplots(figsize=(14, 8))
        
        # Pivot data for grouped bar chart
        pivot_df = df.pivot(index='Provider', columns='Model', values='Total Time (seconds)')
        
        # Create bar chart
        pivot_df.plot(kind='bar', ax=ax, width=0.8)
        
        ax.set_title('Total Time for 10 Image Generation', fontsize=16, fontweight='bold')
        ax.set_xlabel('Provider', fontweight='bold')
        ax.set_ylabel('Total Time (seconds)', fontweight='bold')
        ax.legend(title='Model', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.tick_params(axis='x', rotation=45)
        
        # Add value labels on bars
        for container in ax.containers:
            ax.bar_label(container, fmt='%.1f', rotation=90, padding=3)
        
        plt.tight_layout()
        plt.savefig('plots/total_time_10_images.png', dpi=300, bbox_inches='tight')
        plt.show()
        print("Total time chart saved as 'plots/total_time_10_images.png'")
    
    def create_first_image_time_plot(self):
        """Create bar chart for first image waiting time."""
        print("Creating bar chart for first image waiting time...")
        
        # Prepare data
        plot_data = []
        for record in self.data:
            first_time = None
            if 'first_image_time' in record:
                first_time = record['first_image_time']
            elif 'individual_times' in record and record['individual_times']:
                first_time = record['individual_times'][0]
            
            if first_time is not None:
                plot_data.append({
                    'Provider': record['provider'],
                    'Model': record['model'],
                    'First Image Time (seconds)': first_time
                })
        
        if not plot_data:
            print("No first image time data available")
            return
        
        df = pd.DataFrame(plot_data)
        
        # Create the plot
        fig, ax = plt.subplots(figsize=(14, 8))
        
        # Pivot data for grouped bar chart
        pivot_df = df.pivot(index='Provider', columns='Model', values='First Image Time (seconds)')
        
        # Create bar chart
        pivot_df.plot(kind='bar', ax=ax, width=0.8)
        
        ax.set_title('First Image Generation Waiting Time', fontsize=16, fontweight='bold')
        ax.set_xlabel('Provider', fontweight='bold')
        ax.set_ylabel('Time (seconds)', fontweight='bold')
        ax.legend(title='Model', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.tick_params(axis='x', rotation=45)
        
        # Add value labels on bars
        for container in ax.containers:
            ax.bar_label(container, fmt='%.2f', rotation=90, padding=3)
        
        plt.tight_layout()
        plt.savefig('plots/first_image_waiting_time.png', dpi=300, bbox_inches='tight')
        plt.show()
        print("First image time chart saved as 'plots/first_image_waiting_time.png'")
    
    def print_summary_statistics(self):
        """Print summary statistics of the collected data."""
        print("\n" + "="*60)
        print("PERFORMANCE SUMMARY STATISTICS")
        print("="*60)
        
        for model in self.models:
            print(f"\n{model.upper()}:")
            print("-" * 40)
            
            model_data = [r for r in self.data if r['model'] == model]
            
            for record in model_data:
                provider = record['provider']
                avg_time = record.get('avg_time_per_image', 'N/A')
                total_time = record.get('total_time_10_images', 'N/A')
                first_time = record.get('first_image_time', 'N/A')
                
                if 'individual_times' in record and record['individual_times']:
                    individual_times = record['individual_times']
                    min_time = min(individual_times)
                    max_time = max(individual_times)
                    std_time = np.std(individual_times)
                    
                    print(f"{provider:>10}: Avg={avg_time}s, Total={total_time}s, First={first_time}s")
                    print(f"{'':>10}  Range: {min_time:.2f}s - {max_time:.2f}s, Std: {std_time:.2f}s")
                else:
                    print(f"{provider:>10}: Avg={avg_time}s, Total={total_time}s, First={first_time}s")
    
    def run_analysis(self):
        """Run the complete analysis and generate all plots."""
        print("Starting Yetter AI Performance Analysis")
        print("="*50)
        
        # Collect data
        self.collect_data()
        
        if not self.data:
            print("No data collected. Please check if the files exist.")
            return
        
        # Print summary statistics
        self.print_summary_statistics()
        
        # Generate plots
        print("\n" + "="*50)
        print("GENERATING VISUALIZATIONS")
        print("="*50)
        
        self.create_box_plot_time_per_image()
        self.create_total_time_plot()
        self.create_first_image_time_plot()
        
        print("\n" + "="*50)
        print("ANALYSIS COMPLETE")
        print("="*50)
        print("All plots have been saved to the 'plots/' directory.")
        print("Generated files:")
        print("- plots/time_per_image_boxplot.png")
        print("- plots/total_time_10_images.png")
        print("- plots/first_image_waiting_time.png")


def main():
    """Main function to run the performance analysis."""
    analyzer = PerformanceAnalyzer()
    analyzer.run_analysis()


if __name__ == "__main__":
    main()